---
apiVersion: projectcalico.org/v3
kind: Tier
metadata:
  name: security-team
spec:
  order: 400

---
apiVersion: projectcalico.org/v3
kind: Tier
metadata:
  name: platform-team
spec:
  order: 500
  
---
apiVersion: projectcalico.org/v3
kind: Tier
metadata:
  name: devops-team
spec:
  order: 600