apiVersion:  apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: storefront
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        fw-zone: restricted
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      containers:
      - name: mock-logging
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "probe"
        - "logging:80"
        ports:
        - containerPort: 9000
      - name: mock
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "mock"
        - "--resourcePath"
        - "/mocks/backend-mock.yaml"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: mockconfig
          mountPath: /mocks
      volumes:
      - name: mockconfig
        configMap:
          name: backend

---

kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: storefront
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: storefront
data:
  backend-mock.yaml: |
    apiVersion: peira.tigera.io./v1alpha1
    kind: MockService
    metadata:
       namespace: storefront
       name: backend
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      logLevel: debug
      enableProbe: true
      listenPort: 80
      actions:
      - kind: call
        value: "http://logging"
      - kind: reply
        value: "hello world"
