apiVersion:  apps/v1
kind: Deployment
metadata:
  name: microservice1
  namespace: storefront
  labels:
    app: microservice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
        fw-zone: trusted
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      containers:
      - name: mock-microservice2
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "probe"
        - "microservice2:80"
        ports:
        - containerPort: 9000
      - name: mock-backend
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "probe"
        - "--listenPort"
        - "9001"
        - "backend:80"
        ports:
        - containerPort: 9001
      - name: mock-logging
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "probe"
        - "--listenPort"
        - "9002"
        - "backend:80"
        ports:
        - containerPort: 9002
      - name: mock
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "mock"
        - "--resourcePath"
        - "/mocks/microservice1-mock.yaml"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: mockconfig
          mountPath: /mocks
      volumes:
      - name: mockconfig
        configMap:
          name: microservice1

---

kind: Service
apiVersion: v1
metadata:
  name: microservice1
  namespace: storefront
spec:
  selector:
    app: microservice1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice1
  namespace: storefront
data:
  microservice1-mock.yaml: |
    apiVersion: peira.tigera.io./v1alpha1
    kind: MockService
    metadata:
       namespace: storefront
       name: microservice1
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      logLevel: debug
      enableProbe: true
      listenPort: 80
      actions:
      - kind: call
        value: "http://logging"
      - kind: call
        value: "http://microservice2"
      - kind: call
        value: "http://backend"
      - kind: reply
        value: "hello world"
