apiVersion: v1
kind: Namespace
metadata:
  name: acme

---

apiVersion:  apps/v1
kind: Deployment
metadata:
  name: acme-microservice1
  namespace: acme
  labels:
    app: acme-microservice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acme-microservice1
  template:
    metadata:
      labels:
        app: acme-microservice1
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      containers:
      - name: mock-tor
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do wget 54.37.16.241; sleep 15; done"]
      - name: mock-acme-microservice2
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "probe"
        - "--listenPort"
        - "9002"
        - "acme-microservice2:80"
        ports:
        - containerPort: 9002
      - name: mock
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "mock"
        - "--resourcePath"
        - "/mocks/acme-microservice1-mock.yaml"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: mockconfig
          mountPath: /mocks
      volumes:
      - name: mockconfig
        configMap:
          name: acme-microservice1

---

apiVersion:  apps/v1
kind: Deployment
metadata:
  name: acme-microservice2
  namespace: acme
  labels:
    app: acme-microservice2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acme-microservice2
  template:
    metadata:
      labels:
        app: acme-microservice2
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      containers:
      - name: mock-acme-microservice1
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "probe"
        - "--listenPort"
        - "9002"
        - "acme-microservice1:80"
        ports:
        - containerPort: 9002
      - name: mock
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "mock"
        - "--resourcePath"
        - "/mocks/acme-microservice2-mock.yaml"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: mockconfig
          mountPath: /mocks
      volumes:
      - name: mockconfig
        configMap:
          name: acme-microservice2


---

kind: Service
apiVersion: v1
metadata:
  name: acme-microservice1
  namespace: acme
spec:
  selector:
    app: acme-microservice1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: acme-microservice2
  namespace: acme
spec:
  selector:
    app: acme-microservice2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: acme-microservice1
  namespace: acme
data:
  acme-microservice1-mock.yaml: |
    apiVersion: peira.tigera.io./v1alpha1
    kind: MockService
    metadata:
       namespace: acme
       name: acme-microservice1
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      logLevel: debug
      enableProbe: false
      listenPort: 80
      actions:
      - kind: call
        value: "http://acme-microservice2"
      - kind: reply
        value: "hello world"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: acme-microservice2
  namespace: acme
data:
  acme-microservice2-mock.yaml: |
    apiVersion: peira.tigera.io./v1alpha1
    kind: MockService
    metadata:
       namespace: acme
       name: acme-microservice2
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      logLevel: debug
      enableProbe: false
      listenPort: 80
      actions:
      - kind: call
        value: "http://acme-microservice1"
      - kind: reply
        value: "hello world"