---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: default.nginx
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: nginx
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          compliance: open
  policyTypes:
  - Ingress

---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: default.centos
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: centos
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: nginx
  policyTypes:
  - Egress
