apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sCalicoCloudPolicy
metadata:
  name: cloud-policy-exist
spec:
  match:
    kinds:
      - apiGroups: 
        - "projectcalico.org/v3"
        - "crd.projectcalico.org/v1"
        kinds: ["GlobalNetworkPolicy"]
  