apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sCalicoCloudPolicy
metadata:
  name: cloud-policy-exist
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
  parameters:
    dpname: ["tigera-apiserver"]      
  