apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8scalicocloudpolicy
spec:
  crd:
    spec:
      names:
        kind: K8sCalicoCloudPolicy

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8scalicocloudpolicy
        violation[{"msg": msg, "details": {"missing_policy": missing}}] {
          required := input.parameters.policy_name[_]
          provided := input.review.object.metadata.name
          missing := provided - required
          count(missing) > 0
          msg := sprintf("Not connect to calicocloud")
        }