apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8scalicocloudpolicy
spec:
  crd:
    spec:
      names:
        kind: K8sCalicoCloudPolicy

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8scalicocloudpolicy
        violation[{"msg":msg}] {
          spec_name := input.review.object.metadata.name
          policy_name = "tigera-security.block-alienvault-ipthreatfeed"
          missing := spec_name - policy_name
          count(missing) > 0
          msg := sprintf("Not connect to calicocloud")
        }