apiVersion: projectcalico.org/v3
kind: GlobalReport
metadata:
  name: workload-inventory
  labels:
    deployment: production
spec:
  reportType: inventory
  endpoints:
    namespaces: 
      names:
        ["storefront", "acme", "hipstershop"]
  schedule: '*/15 * * * *'
---
apiVersion: projectcalico.org/v3
kind: GlobalReport
metadata:
  name: workload-network-access
  labels:
    deployment: production
spec:
  reportType: network-access
  endpoints:
    namespaces:
      names:
        ["storefront", "acme", "hipstershop"]
  schedule: '*/15 * * * *'
---
apiVersion: projectcalico.org/v3
kind: GlobalReport
metadata:
  name: workload-policy-audit
  labels:
    deployment: production
spec:
  reportType: policy-audit
  endpoints:
    namespaces: 
      names:
        ["storefront", "acme", "hipstershop"]
  schedule: '*/15 * * * *'