apiVersion:  apps/v1
kind: Deployment
metadata:
  name: rogue
  namespace: storefront
  labels:
    app: rogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rogue
  template:
    metadata:
      labels:
        app: rogue
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      containers:
      - name: mock-c2-infra
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do wget http://www.bunnyboy.com; sleep 15; done"]
      - name: mock-microservice1
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "probe"
        - "microservice1:80"
        - "--frequency"
        - "100ms"
        ports:
        - containerPort: 9000
      - name: mock-microservice2
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "probe"
        - "--listenPort"
        - "9001"
        - "--frequency"
        - "100ms"
        - "microservice2:80"
        ports:
        - containerPort: 9001
      - name: mock-frontend
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "probe"
        - "--listenPort"
        - "9002"
        - "--frequency"
        - "100ms"
        - "frontend:80"
        ports:
        - containerPort: 9002
      - name: mock-backend
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "probe"
        - "--listenPort"
        - "9003"
        - "--frequency"
        - "100ms"
        - "backend:80"
        ports:
        - containerPort: 9003
      - name: mock-logging
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "probe"
        - "--listenPort"
        - "9004"
        - "--frequency"
        - "100ms"
        - "logging:80"
        ports:
        - containerPort: 9004
      - name: mock
        image: quay.io/tigera/peira:v0.2.3
        args:
        - "mock"
        - "--resourcePath"
        - "/mocks/rogue-mock.yaml"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: mockconfig
          mountPath: /mocks
      volumes:
      - name: mockconfig
        configMap:
          name: rogue

---

kind: Service
apiVersion: v1
metadata:
  name: rogue
  namespace: storefront
spec:
  selector:
    app: rogue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: rogue
  namespace: storefront
data:
  rogue-mock.yaml: |
    apiVersion: peira.tigera.io./v1alpha1
    kind: MockService
    metadata:
       namespace: storefront
       name: rogue
    spec:
      imagePullSecrets:
      - name: tigera-pull-secret
      logLevel: debug
      enableProbe: true
      listenPort: 80
      actions:
      - kind: call
        value: "http://frontend"
      - kind: call
        value: "http://backend"
      - kind: call
        value: "http://logging"
      - kind: call
        value: "http://microservice1"
      - kind: call
        value: "http://microservice1"
      - kind: call
        value: "http://microservice2"
      - kind: reply
        value: "hello world"
