apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: bi-analytics-west
  labels:
    type: production
spec:
  interfaceName: eth0
  node: biggie.tigera.io
  expectedIPs:
  - 192.168.0.1
  - 192.168.0.2
  profiles:
  - profile1
  - profile2
  ports:
  - name: some-port
    port: 1234
    protocol: TCP
  - name: another-port
    port: 5432
    protocol: UDP
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: jenkins-build
  labels:
    type: production
spec:
  interfaceName: eth0
  node: tupac.tigera.io
  expectedIPs:
  - 192.168.0.1
  - 192.168.0.2
  profiles:
  - profile1
  - profile2
  ports:
  - name: some-port
    port: 1234
    protocol: TCP
  - name: another-port
    port: 5432
    protocol: UDP